spring:
  application:
    name: gateway-server
  config:
    import: optional:configserver:http://localhost:8888,optional:configserver:http://localhost:8889
  cloud:
    config:
      label: 003-Http-communication
      #fail-fast: true
  profiles:
    active: development
