spring:
  jackson:
    default-property-inclusion: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8100/realms/training
      client:
        registration:
          keycloak:
            client-id: training-client
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8100/realms/training
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    registry-fetch-interval-seconds: 5
management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1
