spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak-server:8100/realms/training
  cloud:
    config:
      fail-fast: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/


