logging:
  level:
    org.javamoney.moneta: OFF
eureka:
  client:
    should-enforce-registration-at-init: true # wymusza rejestrację w service discovery, w innym przypadku uniemożliwia start (wyjątek)
