logging:
  level:
    org.javamoney.moneta: OFF
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server/eureka/
  instance:
    prefer-ip-address: true
    registry-fetch-interval-seconds: 5
