spring:
  jackson:
    default-property-inclusion: always
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/ # adresy serwerów service discovery
    registry-fetch-interval-seconds: 5
management:
  endpoints:
    web:
      exposure:
        include: '*'
