logging:
  level:
    org.javamoney.moneta: OFF
eureka:
  client:
    should-enforce-registration-at-init: true
  instance:
    prefer-ip-address: true
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
    registry-fetch-interval-seconds: 5
