server:
  port: 20000
spring:
  cloud:
    function:
      definition: paymentEventConsumer
    stream:
      bindings:
        paymentEventConsumer-in-0:
          destination: payment-events
          group: ${random.uuid} #shop
#    stream:
#      bindings:
#        productsListener-in-0:
#          destination: products-events
#          group: shop
#          binder: kafka1
#      binders:
#        kafka1:
#          type: kafka
#          environment:
#            spring:
#              cloud:
#                stream:
#                  kafka:
#                    binder:
#                      brokers: localhost:9092
api:
  payments: http://PAYMENTS-SERVICE/payments
discount: 10
