apiVersion: v1
kind: Service
metadata:
  namespace: training
  name: echo-server-service
spec:
  type: NodePort
  selector:
    app-name: echo-server
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
