apiVersion: v1
kind: ConfigMap
metadata:
  name: updater-config-map
  namespace: training
data:
  INTERVAL: '30'
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true  
