spring:
  application:
    name: payments-service
  config:
    import: optional:configserver:http://localhost:8888,optional:configserver:http://localhost:8889
  cloud:
    config:
      label: 004-Async-communication
      #fail-fast: true
  profiles:
    active: development
