server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/landrzejewski/spring-cloud
          search-paths: configuration-files # katalog/katalogi z plikami konfiguracyjnymi
          try-master-branch: false # w przypadku braku brancha master
          skip-ssl-validation: true # w przypadku ogranicze? wynikaj?cych z wykorzystania vpn, proxy
