services:
  postgres-service:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=training
    volumes:
      - users-storage:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d:ro
    networks:
      users-network:
  users-service:
    image: users
    restart: always
    deploy:
      replicas: 3
    networks:
      users-network:
  proxy:
    image: nginx:1.25.2-alpine
    ports:
      - "8080:80"
      - "8081:443"
    networks:
      users-network:
    volumes:
      - ./proxy:/etc/nginx/conf.d:ro
      - ./html:/usr/share/nginx/html
#  client:
#    image: ubuntu:23.10
#    tty: true
#    networks:
#      users-network:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
    networks:
      users-network:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data
volumes:
  users-storage:
networks:
  users-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
